INSERT INTO students (student_id, full_name) VALUES
(1, 'Jackie Robbins'),
(2, 'Mary Gallegos'),
(3, 'Ashley Franklin'),
(4, 'Christopher Deleon'),
(5, 'Sonya King'),
(6, 'Mrs. Jill Brown'),
(7, 'Steven Evans'),
(8, 'Angela Rios'),
(9, 'Amber Singh'),
(10, 'Brittany Henson'),
(11, 'Timothy Mendoza'),
(12, 'Cynthia Sharp'),
(13, 'Monique Lane'),
(14, 'David Stout'),
(15, 'Lori Morrison'),
(16, 'Christopher Davis Jr.'),
(17, 'Nathan Barr'),
(18, 'Lisa May'),
(19, 'Jamie Gregory'),
(20, 'Toni Brown'),
(21, 'Karla Lloyd'),
(22, 'Kayla Larson'),
(23, 'Lisa Hickman'),
(24, 'Melissa Morris'),
(25, 'Melanie Flowers'),
(26, 'Denise Waller'),
(27, 'Mr. Cody Fleming'),
(28, 'Curtis Johnson'),
(29, 'Heather Davis'),
(30, 'Don Parks'),
(31, 'Hunter Mcbride'),
(32, 'Tracy Garcia'),
(33, 'Jason Diaz'),
(34, 'Erik Williams'),
(35, 'Elizabeth Huerta'),
(36, 'Jake Burgess'),
(37, 'Christopher King'),
(38, 'Craig Sanchez'),
(39, 'Mark Baker'),
(40, 'Victoria Lowe'),
(41, 'Tracy Murillo'),
(42, 'Dr. George Johnston'),
(43, 'Christopher Schmidt'),
(44, 'Melanie Cantrell'),
(45, 'Eric Johnson'),
(46, 'Edward Brewer'),
(47, 'Laura Dorsey'),
(48, 'Katie Johnson'),
(49, 'Charles Powers'),
(50, 'Todd Williams')
